# Generated by Django 5.2.6 on 2025-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mYinterface', '0002_bookingsystem_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsystem',
            name='accommodation_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe Ocean Suite'), ('Standard', 'Standard City Room'), ('Romantic', 'Romantic Honeymoon Suite'), ('Family', 'Family Garden Room'), ('Executive', 'Executive Business Suite'), ('Premium', 'Premium Ocean View')], default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
