# Generated by Django 5.2.6 on 2025-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('room_count', models.PositiveIntegerField()),
                ('accommodation_type', models.CharField(choices=[('classic', 'Classic Room'), ('premium', 'Premium Room'), ('junior-suite', 'Junior Suite'), ('luxury-suite', 'Luxury Suite'), ('penthouse', 'Penthouse Suite')], max_length=50, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('primary_guest', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('snap_token', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='room_images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag_ocean_view', models.BooleanField(default=False)),
                ('tag_garden_view', models.BooleanField(default=False)),
                ('tag_city_view', models.BooleanField(default=False)),
                ('tag_mountain_view', models.BooleanField(default=False)),
                ('tag_pool_view', models.BooleanField(default=False)),
                ('tag_popular', models.BooleanField(default=True)),
                ('tag_business', models.BooleanField(default=False)),
                ('tag_family_friendly', models.BooleanField(default=False)),
                ('tag_romantic', models.BooleanField(default=False)),
                ('tag_premium', models.BooleanField(default=False)),
                ('tag_luxury', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_workspace', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_game_console', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_jacuzzi', models.BooleanField(default=False)),
                ('has_coffeemachine', models.BooleanField(default=False)),
                ('has_kingsize_bed', models.BooleanField(default=False)),
                ('has_secure', models.BooleanField(default=False)),
                ('has_bussinessphone', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
