# Generated by Django 5.2.6 on 2025-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('room_count', models.PositiveIntegerField()),
                ('accommodation_type', models.CharField(choices=[('classic', 'Classic Room'), ('premium', 'Premium Room'), ('junior-suite', 'Junior Suite'), ('luxury-suite', 'Luxury Suite'), ('penthouse', 'Penthouse Suite')], max_length=50, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('primary_guest', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('snap_token', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
