# Generated by Django 5.2.7 on 2025-10-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_apps', '0003_alter_bookingsystem_accommodation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ja',
            field=models.TextField(null=True),
        ),
    ]
