"""
Django settings for LonergardenHotel project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!@*b2aeb)0cv3pv+ybbkuw9pk#h-#7nd81wu)0!b#ykmfx0b7-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Lonergarden_site.backend_apps',
    'modeltranslation'    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  #  This handles language switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#Language Switch
USE_I18N = True          # turn on Django internationalization
USE_L10N = True
LANGUAGE_CODE = 'en'     # default language (fallback)
LANGUAGES = [            # languages your site supports
    ('en', 'English'),
    ('id', 'Indonesian'),
    ('ja', 'Japanese'),
    ('fr', 'French'),
    ('de', 'Deutsch'),
    ('es', 'Spanish'),
]
LOCALE_PATHS = [         
    os.path.join(BASE_DIR, 'locale'),    # where translation files (.po / .mo) live
]

ROOT_URLCONF = 'Lonergarden_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Lonergarden_site' / 'frontend_templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Lonergarden_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'LonergardenHotelDB',
    #     'USER': 'postgres',
    #     'PASSWORD': 'admin',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    'default': dj_database_url.config(
        default='postgres://admin:admin@localhost:5432/LonergardenHotelDB', #// Fallback for local testing
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'Lonergarden_site' / 'frontend_templates' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yp.zxia@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'nfib fgpc jmhq goyp'  # Gmail App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

#django handle image

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Midtrans Payment Gateway Settings
MIDTRANS_SERVER_KEY = 'Mid-server-sU9VtjeHfUmu-mD4rkKOUJI-'  # Replace with your actual Server Key
MIDTRANS_CLIENT_KEY = 'Mid-client-yjuZ1OYeZIe1LS3r'          # Replace with your actual Client Key
MIDTRANS_IS_PRODUCTION = False                               # Set to True when deploying to production
MIDTRANS_CALLBACK_URL = 'http://127.0.0.1:8000/midtrans/notification/' # Change base URL for production

CSRF_TRUSTED_ORIGINS = [
    "https://uneradicative-noreen-swashingly.ngrok-free.dev",
]

# Authentication settings
LOGIN_REDIRECT_URL = '/admin/'  # Where to redirect after successful login
LOGOUT_REDIRECT_URL = '/login/'  # Where to redirect after logout